# Generated by Django 4.2 on 2024-07-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0002_permiso_formulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
