# Generated by Django 4.2 on 2024-08-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0003_permiso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
