# Generated by Django 4.2 on 2025-08-02 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0004_permiso_en_uso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permiso',
            old_name='formulario',
            new_name='modulo',
        ),
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('C', 'Crear'), ('R', 'Leer'), ('U', 'Actualizar'), ('D', 'Eliminar'), ('E', 'Exportar')], default='C', max_length=1),
        ),
    ]
