# Generated by Django 4.2 on 2025-08-03 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0005_rename_formulario_permiso_modulo_alter_permiso_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='fechaCreacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=datetime.datetime(2025, 8, 3, 9, 4, 28, 339815), verbose_name='fecha creacion'),
            preserve_default=False,
        ),
    ]
