# Generated by Django 4.2 on 2025-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0006_permiso_fechacreacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='tipo',
            field=models.CharField(choices=[('C', 'Creacion'), ('R', 'Lectura'), ('U', 'Modificacion'), ('D', 'Eliminacion'), ('E', 'Exportar')], default='C', max_length=1),
        ),
    ]
