# Generated by Django 4.2 on 2025-08-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0007_alter_permiso_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
