# Generated by Django 4.2 on 2025-08-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0006_modulo_en_uso'),
        ('permiso', '0008_alter_permiso_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='modulo.modulo'),
        ),
    ]
