# Generated by Django 4.2 on 2025-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permiso', '0012_alter_permiso_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permiso',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
