# Generated by Django 4.2 on 2025-08-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('cedula', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(default='', max_length=250)),
                ('estado_civil', models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo')], default='S', max_length=1)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('documento', models.CharField(choices=[('CI', 'CI'), ('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte')], db_index=True, default='CI', max_length=20, verbose_name='Tipos de documentos')),
                ('fecha_nacimiento', models.DateTimeField()),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('tipo', models.CharField(default='', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Empleado',
                'db_table': 'Empleado',
            },
        ),
    ]
