# Generated by Django 4.2 on 2025-08-16 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
