# Generated by Django 4.2 on 2024-09-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
