# Generated by Django 4.2 on 2024-09-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_en_uso'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='empleado',
            name='documento',
            field=models.CharField(choices=[('CI', 'CI'), ('DNI', 'DNI'), ('PASAPORTE', 'Pasaporte')], db_index=True, default='CI', max_length=20, verbose_name='Tipos de documentos'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Soltero'), ('C', 'Casado'), ('V', 'Viudo')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1),
        ),
    ]
