# Generated by Django 4.2 on 2025-08-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='descripcion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
