# Generated by Django 4.2 on 2025-08-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_modulo_fecha_modificacion_alter_modulo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
