# Generated by Django 4.2 on 2025-08-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_alter_modulo_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='fecha_modificacion',
            field=models.DateTimeField(null=True),
        ),
    ]
