# Generated by Django 4.2 on 2025-08-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0005_alter_modulo_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
