# Generated by Django 4.2 on 2025-09-15 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nacionalidad', '0004_alter_nacionalidad_codigo_alpha2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la ciudad, ej: Asunción.', max_length=150, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(help_text='País al que pertenece la ciudad.', on_delete=django.db.models.deletion.PROTECT, related_name='ciudades', to='nacionalidad.nacionalidad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'Ciudad',
                'ordering': ['nombre'],
            },
        ),
    ]
