# Generated by Django 4.2 on 2025-09-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del servicio, ej: 'Traslado in/out', 'Desayuno'.", max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre el servicio.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
                'ordering': ['nombre'],
            },
        ),
    ]
