# Generated by Django 4.2 on 2025-09-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('habitacion', 'Habitación'), ('paquete', 'Paquete')], default=2, help_text='Define si el servicio es solo para Habitaciones o solo para Paquetes', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterModelTable(
            name='servicio',
            table=None,
        ),
    ]
