# Generated by Django 4.2 on 2025-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0002_servicio_tipo_alter_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('habitacion', 'Habitación'), ('hotel', 'Hotel'), ('paquete', 'Paquete')], help_text='Define si el servicio es solo para Habitaciones o solo para Paquetes', max_length=20),
        ),
    ]
