# Generated by Django 4.2 on 2025-09-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0003_alter_servicio_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='tipo',
            field=models.CharField(choices=[('habitacion', 'Habitación'), ('hotel', 'Hotel'), ('paquete', 'Paquete')], default='paquete', help_text='Define si el servicio es solo para Habitaciones o solo para Paquetes', max_length=20),
        ),
    ]
