# Generated by Django 4.2 on 2025-10-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0004_alter_servicio_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio base del servicio. Puede ser sobreescrito en PaqueteServicio.', max_digits=12),
            preserve_default=False,
        ),
    ]
