# Generated by Django 4.2 on 2026-04-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_servicio_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio base del servicio (legacy). No afecta el cálculo de precios de venta.', max_digits=12, null=True),
        ),
    ]
