# Generated by Django 4.2 on 2025-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('fijo', 'Salario Fijo'), ('comision', 'Comisión'), ('mixto', 'Mixto')], help_text='Tipo de contrato del empleado', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles o reglas adicionales del contrato', null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión por defecto. 0 para contratos de salario fijo', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contrato',
                'db_table': 'TipoContrato',
                'ordering': ['nombre'],
            },
        ),
    ]
