# Generated by Django 4.2 on 2025-08-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_remuneracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRemuneracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del tipo de remuneración. Ej: 'Salario fijo', 'Comisión', 'Mixto'.", max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles o reglas adicionales del contrato', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Remuneracion',
                'verbose_name_plural': 'Tipos de Remuneraciones',
                'db_table': 'TipoRemuneracion',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='TipoContrato',
        ),
    ]
