# Generated by Django 4.2 on 2025-08-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacionalidad',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
