# Generated by Django 4.2 on 2025-08-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0002_nacionalidad_en_uso'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nacionalidad',
            table='Nacionalidad',
        ),
    ]
