# Generated by Django 4.2 on 2025-08-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0003_alter_nacionalidad_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacionalidad',
            name='codigo_alpha2',
            field=models.CharField(error_messages={'unique': 'Ya existe una nacionalidad con este código alpha2.'}, max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='nacionalidad',
            name='nombre',
            field=models.CharField(error_messages={'unique': 'Ya existe una nacionalidad con este nombre.'}, max_length=100, unique=True),
        ),
    ]
