# Generated by Django 4.2 on 2025-10-08 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zona_geografica', '0001_initial'),
        ('nacionalidad', '0004_alter_nacionalidad_codigo_alpha2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacionalidad',
            name='zona_geografica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paises', to='zona_geografica.zonageografica', verbose_name='Zona Geográfica'),
        ),
    ]
