# Generated by Django 4.2 on 2024-03-12 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('permiso', '0002_permiso_formulario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Rol',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_permisos', to='permiso.permiso')),
                ('rol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_permisos', to='rol.rol')),
            ],
            options={
                'verbose_name': 'RolesPermisos',
                'db_table': 'RolesPermisos',
            },
        ),
        migrations.AddField(
            model_name='rol',
            name='permisos',
            field=models.ManyToManyField(related_name='rol_permiso', through='rol.RolesPermisos', to='permiso.permiso'),
        ),
    ]
