# Generated by Django 4.2 on 2024-08-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_rol_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
