# Generated by Django 4.2 on 2025-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0004_rol_fecha_creacion_rol_fecha_modificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
