# Generated by Django 4.2 on 2025-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_alter_rol_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='es_admin',
            field=models.BooleanField(default=False),
        ),
    ]
