# Generated by Django 4.2 on 2025-09-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='precio_habitacion',
            field=models.IntegerField(default=0, help_text='Precio por habitación en el hotel'),
        ),
    ]
