# Generated by Django 4.2 on 2025-09-06 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
        ('hotel', '0002_alter_hotel_precio_habitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda en la que se expresa el precio por habitación', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='moneda.moneda'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='precio_habitacion',
            field=models.DecimalField(decimal_places=2, help_text='Precio por habitación', max_digits=12),
        ),
        migrations.AlterModelTable(
            name='hotel',
            table=None,
        ),
    ]
