# Generated by Django 4.2 on 2025-09-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
        ('hotel', '0003_hotel_moneda_alter_hotel_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='moneda',
            field=models.ForeignKey(default=1, help_text='Moneda en la que se expresa el precio por habitación', on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='moneda.moneda'),
        ),
    ]
