# Generated by Django 4.2 on 2025-09-06 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0001_initial'),
        ('hotel', '0004_alter_hotel_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='destino',
            field=models.ForeignKey(default=1, help_text='Destino al que pertenece el hotel', on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='destino.destino'),
            preserve_default=False,
        ),
    ]
