# Generated by Django 4.2 on 2025-09-06 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_destino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='destino',
        ),
    ]
