# Generated by Django 4.2 on 2025-09-17 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('hotel', '0006_remove_hotel_destino'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='ciudad',
            field=models.ForeignKey(default=1, help_text='Ciudad donde se encuentra el hotel', on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='ciudad.ciudad'),
            preserve_default=False,
        ),
    ]
