# Generated by Django 4.2 on 2025-09-18 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('moneda', '0001_initial'),
        ('ciudad', '0001_initial'),
        ('hotel', '0007_hotel_ciudad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadenaHotelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadena Hotelera',
                'verbose_name_plural': 'Cadenas Hoteleras',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='estrellas',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='hotel',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='hoteles', to='servicio.servicio'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='ciudad.ciudad'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hoteles', to='moneda.moneda'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='precio_habitacion',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='hotel',
            name='cadena',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoteles', to='hotel.cadenahotelera'),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('single', 'Single'), ('doble', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite'), ('standard', 'Standard')], max_length=20)),
                ('capacidad', models.PositiveSmallIntegerField(default=1)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.hotel')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='moneda.moneda')),
                ('servicios', models.ManyToManyField(blank=True, related_name='habitaciones', to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
                'ordering': ['hotel', 'numero'],
                'unique_together': {('hotel', 'numero')},
            },
        ),
    ]
