# Generated by Django 4.2 on 2025-09-18 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_cadenahotelera_hotel_direccion_hotel_estrellas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='precio_habitacion',
        ),
    ]
