# Generated by Django 4.2 on 2025-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_hotel_moneda_remove_hotel_precio_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(choices=[('single', 'Single'), ('doble', 'Doble'), ('triple', 'Triple'), ('suite', 'Suite'), ('premium', 'Premium')], max_length=20),
        ),
    ]
