# Generated by Django 4.2 on 2026-02-11 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('capacidad', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Habitación',
                'verbose_name_plural': 'Tipos de Habitación',
                'db_table': 'tipo_habitacion',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='habitacion',
            options={'ordering': ['hotel'], 'verbose_name': 'Habitación', 'verbose_name_plural': 'Habitaciones'},
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='capacidad',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(blank=True, help_text='Tipo de habitación (se hará NOT NULL después de la migración de datos)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='hotel.tipohabitacion'),
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'tipo_habitacion')},
        ),
    ]
