# Generated by Django 4.2 on 2026-02-11 23:37

from django.db import migrations


TIPO_DISPLAY = {
    "single": "Single",
    "doble": "Doble",
    "triple": "Triple",
    "suite": "Suite",
    "premium": "Premium",
}


def poblar_tipo_habitacion(apps, schema_editor):
    """
    Para cada combinación única de (tipo, numero, capacidad) en Habitacion,
    crea un TipoHabitacion con nombre = "{TipoDisplay} {numero}" y asigna la FK.
    Ejemplo: tipo="doble", numero="Standard" → "Doble Standard"
    """
    Habitacion = apps.get_model("hotel", "Habitacion")
    TipoHabitacion = apps.get_model("hotel", "TipoHabitacion")

    # Cache para evitar duplicados
    cache = {}

    for hab in Habitacion.objects.all():
        tipo_display = TIPO_DISPLAY.get(hab.tipo, hab.tipo or "")
        numero = (hab.numero or "").strip()

        # Construir nombre: "Doble Standard", "Suite Presidencial", etc.
        if numero and numero.lower() != tipo_display.lower():
            nombre = f"{tipo_display} {numero}"
        else:
            nombre = tipo_display

        nombre = nombre.strip()
        if not nombre:
            nombre = "Sin tipo"

        capacidad = hab.capacidad or 1

        # Buscar o crear TipoHabitacion
        cache_key = nombre.lower()
        if cache_key not in cache:
            tipo_hab, _ = TipoHabitacion.objects.get_or_create(
                nombre=nombre,
                defaults={"capacidad": capacidad, "activo": True},
            )
            cache[cache_key] = tipo_hab

        hab.tipo_habitacion = cache[cache_key]
        hab.save(update_fields=["tipo_habitacion"])


def revertir_tipo_habitacion(apps, schema_editor):
    """Reverse: no-op, los campos legacy siguen existiendo."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_crear_tipo_habitacion_y_modificar_habitacion'),
    ]

    operations = [
        migrations.RunPython(poblar_tipo_habitacion, revertir_tipo_habitacion),
    ]
