# Generated by Django 4.2 on 2026-02-11 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_poblar_tipo_habitacion'),
    ]

    operations = [
        # Hacer tipo_habitacion NOT NULL
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='habitaciones',
                to='hotel.tipohabitacion',
                help_text='Tipo de habitación',
            ),
        ),
        # Eliminar campos legacy
        migrations.RemoveField(
            model_name='habitacion',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='habitacion',
            name='capacidad',
        ),
    ]
