# Generated by Django 4.2 on 2026-04-12 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0002_cotizacionmoneda_and_more'),
        ('hotel', '0015_simplificar_tipos_habitacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='habitaciones', to='moneda.moneda'),
        ),
    ]
