# Generated by Django 4.2 on 2025-09-05 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la distribuidora u operador.', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre la distribuidora.', null=True)),
                ('telefono', models.CharField(blank=True, help_text='Número de contacto de la distribuidora (opcional).', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo de contacto de la distribuidora (opcional).', max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Distribuidora',
                'verbose_name_plural': 'Distribuidoras',
                'db_table': 'Distribuidora',
                'ordering': ['nombre'],
            },
        ),
    ]
