# Generated by Django 4.2 on 2025-11-12 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobante', '0003_migrar_vouchers_a_pasajeros'),
        ('empleado', '0004_alter_empleado_salario'),
        ('facturacion', '0018_facturaelectronica_moneda_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AperturaCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_apertura', models.CharField(editable=False, help_text='Código único: APR-2025-0001', max_length=20, unique=True)),
                ('fecha_hora_apertura', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de apertura')),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Monto inicial con el que se abre (fondo de cambio)', max_digits=15)),
                ('observaciones_apertura', models.TextField(blank=True, help_text='Observaciones al momento de abrir', null=True)),
                ('esta_abierta', models.BooleanField(default=True, help_text='True si la caja sigue abierta, False si ya fue cerrada')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Apertura de Caja',
                'verbose_name_plural': 'Aperturas de Caja',
                'db_table': 'AperturaCaja',
                'ordering': ['-fecha_hora_apertura'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movimiento', models.CharField(editable=False, help_text='Código único: MOV-2025-0001', max_length=20, unique=True)),
                ('tipo_movimiento', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], help_text='Ingreso o Egreso', max_length=20)),
                ('concepto', models.CharField(help_text='Concepto del movimiento', max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del movimiento', max_digits=15)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_debito', 'Tarjeta de Débito'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('qr', 'Pago QR'), ('otro', 'Otro')], help_text='Método de pago utilizado', max_length=20)),
                ('referencia', models.CharField(blank=True, help_text='Referencia del movimiento (número de factura, recibo, etc.)', max_length=100, null=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del movimiento', null=True)),
                ('fecha_hora_movimiento', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del movimiento')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('apertura_caja', models.ForeignKey(help_text='Apertura de caja a la que pertenece este movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='arqueo_caja.aperturacaja')),
                ('comprobante', models.ForeignKey(blank=True, help_text='Comprobante asociado (si aplica)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_caja', to='comprobante.comprobantepago')),
                ('usuario_registro', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'db_table': 'MovimientoCaja',
                'ordering': ['-fecha_hora_movimiento'],
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cierre', models.CharField(editable=False, help_text='Código único: CIE-2025-0001', max_length=20, unique=True)),
                ('fecha_hora_cierre', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de cierre')),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, help_text='Total ingresado en efectivo', max_digits=15)),
                ('total_tarjetas', models.DecimalField(decimal_places=2, default=0, help_text='Total de tarjetas (débito + crédito)', max_digits=15)),
                ('total_transferencias', models.DecimalField(decimal_places=2, default=0, help_text='Total de transferencias', max_digits=15)),
                ('total_cheques', models.DecimalField(decimal_places=2, default=0, help_text='Total de cheques', max_digits=15)),
                ('total_otros_ingresos', models.DecimalField(decimal_places=2, default=0, help_text='Otros métodos de pago', max_digits=15)),
                ('total_egresos', models.DecimalField(decimal_places=2, default=0, help_text='Total de egresos del turno', max_digits=15)),
                ('saldo_teorico_efectivo', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo esperado en efectivo = monto_inicial + efectivo - egresos', max_digits=15, null=True)),
                ('saldo_teorico_total', models.DecimalField(blank=True, decimal_places=2, help_text='Saldo total esperado (todos los métodos)', max_digits=15, null=True)),
                ('saldo_real_efectivo', models.DecimalField(blank=True, decimal_places=2, help_text='Efectivo físicamente contado', max_digits=15, null=True)),
                ('detalle_billetes', models.JSONField(blank=True, help_text='Detalle del conteo de billetes por denominación', null=True)),
                ('diferencia_efectivo', models.DecimalField(blank=True, decimal_places=2, help_text='Diferencia = saldo_real - saldo_teorico', max_digits=15, null=True)),
                ('diferencia_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de diferencia respecto al teórico', max_digits=5, null=True)),
                ('observaciones_cierre', models.TextField(blank=True, help_text='Observaciones generales del cierre', null=True)),
                ('justificacion_diferencia', models.TextField(blank=True, help_text='Justificación de la diferencia (si la hay)', null=True)),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='True si la diferencia supera el umbral permitido')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, help_text='Fecha y hora de autorización', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('apertura_caja', models.OneToOneField(help_text='Apertura de caja que se está cerrando', on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='arqueo_caja.aperturacaja')),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Supervisor que autorizó el cierre con diferencia', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_autorizados', to='empleado.empleado')),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': 'Cierres de Caja',
                'db_table': 'CierreCaja',
                'ordering': ['-fecha_hora_cierre'],
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo (ej: Caja Principal, Caja 1)', max_length=100)),
                ('numero_caja', models.PositiveIntegerField(help_text='Número único de la caja', unique=True)),
                ('emite_facturas', models.BooleanField(default=True, help_text='Indica si esta caja puede emitir facturas electrónicas')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional', null=True)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física de la caja', max_length=200, null=True)),
                ('estado_actual', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='cerrada', max_length=20)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, help_text='Saldo actual en la caja', max_digits=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('punto_expedicion', models.ForeignKey(blank=True, help_text='Punto de expedición asociado (si emite facturas desde esta caja)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cajas', to='facturacion.puntoexpedicion')),
            ],
            options={
                'verbose_name': 'Caja',
                'verbose_name_plural': 'Cajas',
                'db_table': 'Caja',
                'ordering': ['numero_caja'],
            },
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='caja',
            field=models.ForeignKey(help_text='Caja que se está abriendo', on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='arqueo_caja.caja'),
        ),
        migrations.AddField(
            model_name='aperturacaja',
            name='responsable',
            field=models.ForeignKey(help_text='Empleado responsable del turno', on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caja', to='empleado.empleado'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['apertura_caja', 'tipo_movimiento'], name='MovimientoC_apertur_53e9b5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['fecha_hora_movimiento'], name='MovimientoC_fecha_h_dbaca6_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocaja',
            index=models.Index(fields=['comprobante'], name='MovimientoC_comprob_24855b_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['apertura_caja'], name='CierreCaja_apertur_4a11bf_idx'),
        ),
        migrations.AddIndex(
            model_name='cierrecaja',
            index=models.Index(fields=['fecha_hora_cierre'], name='CierreCaja_fecha_h_ee6401_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['caja', 'esta_abierta'], name='AperturaCaj_caja_id_e68748_idx'),
        ),
        migrations.AddIndex(
            model_name='aperturacaja',
            index=models.Index(fields=['responsable', 'fecha_hora_apertura'], name='AperturaCaj_respons_6bd307_idx'),
        ),
    ]
