# Generated by Django 4.2 on 2025-11-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo_caja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.CharField(editable=False, help_text='Número único de la caja con formato 001, 002, 003...', max_length=10, unique=True),
        ),
    ]
