# Generated by Django 4.2 on 2025-11-15 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_facturaelectronica_moneda_original_and_more'),
        ('arqueo_caja', '0002_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='emite_facturas',
        ),
        migrations.RemoveField(
            model_name='caja',
            name='ubicacion',
        ),
        migrations.AlterField(
            model_name='caja',
            name='punto_expedicion',
            field=models.OneToOneField(help_text='Punto de expedición exclusivo de esta caja (relación 1:1)', on_delete=django.db.models.deletion.PROTECT, related_name='caja', to='facturacion.puntoexpedicion'),
        ),
    ]
