# Generated by Django 4.2 on 2025-11-15 18:28

from django.db import migrations, models


def update_numero_caja_format(apps, schema_editor):
    """
    Actualiza el formato de numero_caja para incluir el código del establecimiento.
    Formato anterior: "004"
    Formato nuevo: "001-004" (ESTABLECIMIENTO-PUNTO_EXPEDICION)
    """
    Caja = apps.get_model('arqueo_caja', 'Caja')

    for caja in Caja.objects.select_related('punto_expedicion__establecimiento').all():
        if caja.punto_expedicion and caja.punto_expedicion.establecimiento:
            establecimiento_codigo = caja.punto_expedicion.establecimiento.codigo
            pe_codigo = caja.punto_expedicion.codigo
            nuevo_numero = f"{establecimiento_codigo}-{pe_codigo}"

            # Solo actualizar si el formato es diferente
            if caja.numero_caja != nuevo_numero:
                caja.numero_caja = nuevo_numero
                caja.save(update_fields=['numero_caja'])


def revert_numero_caja_format(apps, schema_editor):
    """
    Revierte el formato de numero_caja al formato anterior (solo código del PE).
    """
    Caja = apps.get_model('arqueo_caja', 'Caja')

    for caja in Caja.objects.select_related('punto_expedicion').all():
        if caja.punto_expedicion:
            # Extraer solo el código del PE (después del guion)
            if '-' in caja.numero_caja:
                pe_codigo = caja.punto_expedicion.codigo
                caja.numero_caja = pe_codigo
                caja.save(update_fields=['numero_caja'])


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo_caja', '0003_remove_caja_emite_facturas_remove_caja_ubicacion_and_more'),
    ]

    operations = [
        # Primero, eliminar temporalmente la restricción unique
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.CharField(editable=False, help_text='Número de la caja (formato: ESTABLECIMIENTO-PUNTO_EXPEDICION)', max_length=20, unique=False),
        ),
        # Actualizar los valores existentes
        migrations.RunPython(update_numero_caja_format, revert_numero_caja_format),
        # Restaurar la restricción unique
        migrations.AlterField(
            model_name='caja',
            name='numero_caja',
            field=models.CharField(editable=False, help_text='Número de la caja (formato: ESTABLECIMIENTO-PUNTO_EXPEDICION)', max_length=20, unique=True),
        ),
    ]
