# Generated by Django 4.2 on 2025-11-15 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0018_facturaelectronica_moneda_original_and_more'),
        ('arqueo_caja', '0004_alter_caja_numero_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='punto_expedicion',
            field=models.OneToOneField(error_messages={'unique': 'Ya existe una caja con este punto de expedición.'}, help_text='Punto de expedición exclusivo de esta caja (relación 1:1)', on_delete=django.db.models.deletion.PROTECT, related_name='caja', to='facturacion.puntoexpedicion'),
        ),
    ]
