# Generated by Django 4.2 on 2025-11-19 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arqueo_caja', '0005_alter_caja_punto_expedicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierrecaja',
            name='diferencia_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de diferencia respecto al teórico', max_digits=10, null=True),
        ),
    ]
