# Generated by Django 4.2 on 2025-09-06 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nacionalidad', '0004_alter_nacionalidad_codigo_alpha2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del destino.', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales sobre el destino.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('pais', models.ForeignKey(blank=True, help_text='País al que pertenece el destino (opcional).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='nacionalidad.nacionalidad')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'db_table': 'Destino',
                'ordering': ['nombre'],
            },
        ),
    ]
