# Generated by Django 4.2 on 2025-09-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_remove_hotel_destino'),
        ('destino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destino',
            name='hoteles',
            field=models.ManyToManyField(blank=True, help_text='Hoteles disponibles en este destino', related_name='destinos', to='hotel.hotel'),
        ),
    ]
