# Generated by Django 4.2 on 2025-09-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0004_alter_nacionalidad_codigo_alpha2_and_more'),
        ('destino', '0002_destino_hoteles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destino',
            name='pais',
            field=models.ForeignKey(default=1, help_text='País al que pertenece el destino.', on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='nacionalidad.nacionalidad'),
            preserve_default=False,
        ),
    ]
