# Generated by Django 4.2 on 2025-09-15 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciudad', '0001_initial'),
        ('destino', '0003_alter_destino_pais'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['ciudad__nombre'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
        migrations.RemoveField(
            model_name='destino',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='destino',
            name='pais',
        ),
        migrations.AddField(
            model_name='destino',
            name='ciudad',
            field=models.ForeignKey(default=1, help_text='Ciudad que representa este destino.', on_delete=django.db.models.deletion.PROTECT, related_name='destinos', to='ciudad.ciudad'),
            preserve_default=False,
        ),
    ]
