# Generated by Django 4.2 on 2025-09-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0004_alter_destino_options_remove_destino_nombre_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='destino',
            constraint=models.UniqueConstraint(fields=('ciudad',), name='unique_destino_por_ciudad'),
        ),
    ]
