# Generated by Django 4.2 on 2025-09-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0005_destino_unique_destino_por_ciudad'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='destino',
            name='unique_destino_por_ciudad',
        ),
    ]
