# Generated by Django 4.2 on 2025-09-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0006_remove_destino_unique_destino_por_ciudad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['ciudad'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
    ]
