# Generated by Django 4.2 on 2025-09-20 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destino', '0007_alter_destino_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destino',
            options={'ordering': ['ciudad__nombre'], 'verbose_name': 'Destino', 'verbose_name_plural': 'Destinos'},
        ),
    ]
