# Generated by Django 4.2 on 2025-09-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre del tipo de paquete. Ej: 'Aéreo', 'Terrestre', 'Acuático', 'Espacial'.", max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles o características del tipo de paquete.', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('en_uso', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Paquete',
                'verbose_name_plural': 'Tipos de Paquetes',
                'db_table': 'TipoPaquete',
                'ordering': ['nombre'],
            },
        ),
    ]
