# Generated by Django 4.2 on 2025-09-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre de la moneda. Ej: 'Dólar', 'Guaraní'", max_length=50, unique=True)),
                ('simbolo', models.CharField(help_text="Símbolo de la moneda. Ej: '$', 'Gs'", max_length=5)),
                ('codigo', models.CharField(help_text="Código de la moneda. Ej: 'USD', 'PYG'", max_length=3, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si la moneda está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['nombre'],
            },
        ),
    ]
