# Generated by Django 4.2 on 2025-11-09 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionMoneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_en_guaranies', models.DecimalField(decimal_places=2, help_text='Valor de 1 unidad de la moneda en guaraníes. Ej: 1 USD = 7300 Gs', max_digits=12)),
                ('fecha_vigencia', models.DateField(help_text='Fecha para la cual es válida esta cotización')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre esta cotización', null=True)),
                ('moneda', models.ForeignKey(help_text='Moneda cuya cotización se registra (ej: USD)', on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='moneda.moneda')),
                ('usuario_registro', models.ForeignKey(blank=True, help_text='Usuario que registró esta cotización', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotización de Moneda',
                'verbose_name_plural': 'Cotizaciones de Monedas',
                'ordering': ['-fecha_vigencia'],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacionmoneda',
            index=models.Index(fields=['moneda', 'fecha_vigencia'], name='moneda_coti_moneda__5c01f1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacionmoneda',
            unique_together={('moneda', 'fecha_vigencia')},
        ),
    ]
