# Generated by Django 4.2 on 2025-08-21 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_documento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tipodocumento',
            table='TipoDocumento',
        ),
    ]
