# Generated by Django 4.2 on 2025-09-11 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0005_alter_personafisica_options_and_more'),
        ('paquete', '0005_paquete_servicios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('cantidad_pasajeros', models.PositiveIntegerField(help_text='Cantidad total de pasajeros incluidos en la reserva')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto abonado hasta el momento', max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('incompleta', 'Incompleta'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='pendiente', help_text='Estado actual de la reserva', max_length=20)),
                ('paquete', models.ForeignKey(help_text='Paquete turístico reservado', on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='paquete.paquete')),
                ('titular', models.ForeignKey(help_text='Persona que realiza la reserva (titular de la compra)', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_titulares', to='persona.personafisica')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'Reserva',
            },
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=False, help_text='Indica si este pasajero es el titular de la reserva')),
                ('ticket_numero', models.CharField(blank=True, help_text='Número de ticket asignado (si aplica)', max_length=100, null=True)),
                ('voucher_codigo', models.CharField(blank=True, help_text='Código de voucher asignado (si aplica)', max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='persona.personafisica')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasajeros', to='reserva.reserva')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'db_table': 'Pasajero',
            },
        ),
    ]
