# Generated by Django 4.2 on 2025-09-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_reserva_activo_reserva_fecha_modificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='codigo',
            field=models.CharField(default='RSV-2025-001', editable=False, help_text='Código único de la reserva', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='observacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la reserva', null=True),
        ),
    ]
