# Generated by Django 4.2 on 2025-09-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_reserva_codigo_reserva_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='codigo',
            field=models.CharField(editable=False, help_text='Código único de la reserva', max_length=20, unique=True),
        ),
    ]
