# Generated by Django 4.2 on 2025-10-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_servicio_precio'),
        ('reserva', '0004_alter_reserva_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaServiciosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, help_text='Cantidad de personas que tomarán este servicio')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por persona al momento de la contratación', max_digits=10)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se agregó el servicio a la reserva')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones sobre este servicio adicional', null=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el servicio adicional está activo')),
                ('reserva', models.ForeignKey(help_text='Reserva a la que se agrega el servicio', on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='reserva.reserva')),
                ('servicio', models.ForeignKey(help_text='Servicio adicional contratado', on_delete=django.db.models.deletion.PROTECT, related_name='reservas_adicionales', to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Servicio Adicional de Reserva',
                'verbose_name_plural': 'Servicios Adicionales de Reserva',
                'db_table': 'ReservaServiciosAdicionales',
                'ordering': ['-fecha_agregado'],
            },
        ),
    ]
