# Generated by Django 4.2 on 2025-10-14 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0014_alter_salidapaquete_cupo_cupohabitacionsalida'),
        ('reserva', '0005_reservaserviciosadicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='habitacion',
            field=models.ForeignKey(blank=True, help_text='Habitación seleccionada para la reserva', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hotel',
            field=models.ForeignKey(blank=True, help_text='Hotel seleccionado para la reserva', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='salida',
            field=models.ForeignKey(blank=True, help_text='Salida específica del paquete seleccionada por el cliente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='paquete.salidapaquete'),
        ),
    ]
