# Generated by Django 4.2 on 2025-10-15 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_reserva_habitacion_reserva_hotel_reserva_salida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cantidad_pasajeros',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de pasajeros. Si no se especifica, se toma de la capacidad de la habitación', null=True),
        ),
    ]
