# Generated by Django 4.2 on 2025-10-15 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_alter_reserva_cantidad_pasajeros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hotel',
        ),
    ]
