# Generated by Django 4.2 on 2025-10-15 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_personafisica_options_and_more'),
        ('reserva', '0008_remove_reserva_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Persona que realiza la reserva (titular/responsable de la compra). Opcional.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_titulares', to='persona.personafisica'),
        ),
    ]
