# Generated by Django 4.2 on 2025-10-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_alter_reserva_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado por pasajero al momento de la reserva (incluye habitación + ganancia/comisión + servicios base del paquete)', max_digits=12, null=True),
        ),
    ]
