# Generated by Django 4.2 on 2025-10-17 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_reserva_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='datos_completos',
            field=models.BooleanField(default=False, help_text='Indica si todos los datos de pasajeros están cargados'),
        ),
    ]
