# Generated by Django 4.2 on 2025-10-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0011_reserva_datos_completos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='precio_asignado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio acordado para este pasajero (normalmente precio_unitario de la reserva)', max_digits=12, null=True),
        ),
    ]
