# Generated by Django 4.2 on 2025-10-28 16:20

from django.db import migrations, models
import django.db.models.deletion


def migrar_reservas_incompletas(apps, schema_editor):
    """
    Migra todas las reservas con estado 'incompleta' (legacy) a 'confirmada'.
    El flag datos_completos indicará si tiene o no todos los datos de pasajeros.
    """
    Reserva = apps.get_model('reserva', 'Reserva')

    # Buscar y actualizar todas las reservas con estado 'incompleta'
    reservas_actualizadas = Reserva.objects.filter(estado='incompleta').update(estado='confirmada')

    if reservas_actualizadas > 0:
        print(f"[OK] Migradas {reservas_actualizadas} reserva(s) de 'incompleta' a 'confirmada'")


def revertir_migracion(apps, schema_editor):
    """
    No revertir - las reservas con estado 'confirmada' y datos_completos=False
    ya reflejan correctamente su estado.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_personafisica_options_and_more'),
        ('reserva', '0012_pasajero_precio_asignado'),
    ]

    operations = [
        # Primero migrar los datos (antes de cambiar las choices)
        migrations.RunPython(migrar_reservas_incompletas, revertir_migracion),

        # Luego actualizar el modelo
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmado'), ('finalizada', 'Finalizado'), ('cancelada', 'Cancelado')], default='pendiente', help_text='Estado actual de la reserva', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='titular',
            field=models.ForeignKey(blank=True, help_text='Persona que realiza la reserva (titular/responsable de la compra). Requerido al crear nuevas reservas.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_titulares', to='persona.personafisica'),
        ),
    ]
