# Generated by Django 4.2 on 2025-10-30 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0013_eliminar_estado_incompleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasajero',
            name='por_asignar',
            field=models.BooleanField(default=False, help_text='Indica si este pasajero está pendiente de asignación (True) o tiene datos reales (False)'),
        ),
    ]
