# Generated by Django 4.2 on 2025-11-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_pasajero_por_asignar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='modalidad_facturacion',
            field=models.CharField(blank=True, choices=[('global', 'Facturación Global (Una factura total)'), ('individual', 'Facturación Individual (Por pasajero)')], help_text='Modalidad de facturación elegida al confirmar la reserva. NULL mientras esté pendiente.', max_length=20, null=True),
        ),
    ]
