# Generated by Django 4.2 on 2025-11-06 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_reserva_modalidad_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='condicion_pago',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('credito', 'Crédito')], help_text='Condición de pago elegida al confirmar la reserva (contado o crédito). NULL mientras esté pendiente.', max_length=20, null=True),
        ),
    ]
