# Generated by Django 4.2 on 2025-11-19 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0016_reserva_condicion_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='monto_pagado',
        ),
    ]
