# Generated by Django 4.2 on 2025-11-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0017_remove_reserva_monto_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cupos_liberados',
            field=models.BooleanField(default=False, help_text='Indica si los cupos asociados a la reserva ya fueron liberados'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en la que la reserva fue cancelada', null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, help_text='Motivo registrado al cancelar la reserva', max_length=255, null=True),
        ),
    ]
