# Generated by Django 4.2 on 2025-11-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0018_reserva_cupos_liberados_reserva_fecha_cancelacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion_codigo',
            field=models.CharField(blank=True, choices=[('cliente_solicitud', 'Cancelación voluntaria del cliente'), ('cambio_planes', 'Cambio de planes del cliente'), ('problemas_salud', 'Problemas de salud'), ('problemas_documentacion', 'Problemas con documentación'), ('falta_pago', 'Cancelación automática por falta de pago'), ('fuerza_mayor', 'Fuerza mayor / Caso fortuito'), ('error_reserva', 'Error en la reserva'), ('otro', 'Otro motivo')], help_text='Código del motivo de cancelación', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='motivo_cancelacion',
            field=models.TextField(blank=True, help_text='Observaciones adicionales sobre la cancelación', null=True),
        ),
    ]
