# Generated by Django 4.2 on 2025-11-21 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0019_reserva_motivo_cancelacion_codigo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='motivo_cancelacion_codigo',
        ),
        migrations.AddField(
            model_name='reserva',
            name='motivo_cancelacion_id',
            field=models.CharField(blank=True, choices=[('1', 'Cancelación voluntaria del cliente'), ('2', 'Cambio de planes del cliente'), ('3', 'Problemas de salud'), ('4', 'Problemas con documentación'), ('5', 'Cancelación automática por falta de pago'), ('6', 'Fuerza mayor / Caso fortuito'), ('7', 'Error en la reserva'), ('8', 'Otro motivo')], help_text='ID del motivo de cancelación', max_length=2, null=True),
        ),
    ]
