# Generated by Django 4.2 on 2025-08-23 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puesto', '0001_initial'),
        ('persona', '0005_alter_personafisica_options_and_more'),
        ('tipo_remuneracion', '0002_tiporemuneracion_delete_tipocontrato'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, default=0.0, help_text='Salario base del empleado, si aplica', max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de comisión del empleado, si aplica', max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.OneToOneField(help_text='Persona asociada al empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to='persona.persona')),
                ('puesto', models.ForeignKey(help_text='Puesto que ocupa el empleado', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='puesto.puesto')),
                ('tipo_remuneracion', models.ForeignKey(help_text='Tipo de remuneración del empleado', on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='tipo_remuneracion.tiporemuneracion')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
