# Generated by Django 4.2 on 2025-08-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Salario base del empleado, si aplica', max_digits=10),
        ),
    ]
