# Generated by Django 4.2 on 2025-08-23 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_alter_empleado_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
