# Generated by Django 4.2 on 2025-08-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0003_empleado_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.IntegerField(default=0, help_text='Salario base del empleado, si aplica'),
        ),
    ]
