# Generated by Django 4.2 on 2025-09-06 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destino', '0001_initial'),
        ('distribuidora', '0001_initial'),
        ('tipo_paquete', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('propio', models.BooleanField(default=True, help_text='Marcar si el paquete es propio de la empresa. Si es False, debe tener una distribuidora.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(blank=True, help_text='Imagen representativa del paquete', null=True, upload_to='paquetes/')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='destino.destino')),
                ('distribuidora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='distribuidora.distribuidora')),
                ('tipo_paquete', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='tipo_paquete.tipopaquete')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'Paquete',
                'ordering': ['nombre'],
            },
        ),
    ]
