# Generated by Django 4.2 on 2025-09-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='cantidad_pasajeros',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de pasajeros (solo para paquetes terrestres propios)', null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Fecha de fin del paquete', null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='fecha_inicio',
            field=models.DateField(blank=True, help_text='Fecha de inicio del paquete', null=True),
        ),
        migrations.AddField(
            model_name='paquete',
            name='personalizado',
            field=models.BooleanField(default=False, help_text='Si está marcado, no requiere fechas de salida'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio total del paquete'),
        ),
        migrations.AddField(
            model_name='paquete',
            name='sena',
            field=models.IntegerField(default=0, help_text='Pago inicial o seña del paquete'),
        ),
    ]
