# Generated by Django 4.2 on 2025-09-07 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
        ('paquete', '0002_paquete_cantidad_pasajeros_paquete_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='moneda',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='moneda.moneda'),
        ),
    ]
