# Generated by Django 4.2 on 2025-09-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
        ('paquete', '0003_paquete_moneda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paquetes', to='moneda.moneda'),
        ),
    ]
