# Generated by Django 4.2 on 2025-09-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0001_initial'),
        ('paquete', '0004_alter_paquete_moneda'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='servicios',
            field=models.ManyToManyField(blank=True, help_text='Lista de servicios incluidos en el paquete', related_name='paquetes', to='servicio.servicio'),
        ),
    ]
