# Generated by Django 4.2 on 2025-09-21 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_habitacion_tipo'),
        ('moneda', '0001_initial'),
        ('paquete', '0005_paquete_servicios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='personalizado',
            field=models.BooleanField(default=False, help_text='Si está marcado, no requiere fechas de salida generales.'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='precio',
            field=models.IntegerField(default=0, help_text='Precio referencial'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='propio',
            field=models.BooleanField(default=True, help_text='Si es False, debe tener una distribuidora asociada.'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='sena',
            field=models.IntegerField(default=0, help_text='Pago inicial o seña referencial'),
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('paquetes', models.ManyToManyField(blank=True, help_text='Paquetes que pertenecen a esta temporada', related_name='temporadas', to='paquete.paquete')),
            ],
            options={
                'verbose_name': 'Temporada',
                'verbose_name_plural': 'Temporadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='SalidaPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('precio_actual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cupo', models.PositiveIntegerField(default=0, help_text='Cupo total de pasajeros')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='moneda.moneda')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='paquete.paquete')),
                ('temporada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas', to='paquete.temporada')),
            ],
            options={
                'verbose_name': 'Salida de Paquete',
                'verbose_name_plural': 'Salidas de Paquete',
                'ordering': ['fecha_salida'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='paquete.salidapaquete')),
            ],
            options={
                'verbose_name': 'Historial Precio Paquete',
                'verbose_name_plural': 'Historiales Precio Paquete',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HistorialPrecioHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='hotel.habitacion')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_habitaciones', to='paquete.salidapaquete')),
            ],
            options={
                'verbose_name': 'Historial Precio Habitación',
                'verbose_name_plural': 'Historiales Precio Habitación',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
