# Generated by Django 4.2 on 2025-09-23 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0006_alter_paquete_fecha_fin_alter_paquete_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='paquete',
            name='sena',
        ),
    ]
