# Generated by Django 4.2 on 2025-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0007_remove_paquete_fecha_fin_remove_paquete_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidapaquete',
            name='fecha_regreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='senia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto de la seña del pago', max_digits=12, null=True),
        ),
    ]
