# Generated by Django 4.2 on 2025-09-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_alter_habitacion_tipo'),
        ('paquete', '0008_salidapaquete_fecha_regreso_salidapaquete_senia'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidapaquete',
            name='hoteles',
            field=models.ManyToManyField(help_text='Hoteles disponibles para esta salida del paquete', related_name='salidas_paquete', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio máximo de las habitaciones por cantidad de noches (puede ser nulo)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_actual',
            field=models.DecimalField(decimal_places=2, help_text='Precio mínimo calculado (por persona, según habitación más económica)', max_digits=12),
        ),
    ]
