# Generated by Django 4.2 on 2025-09-28 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0009_salidapaquete_hoteles_salidapaquete_precio_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidapaquete',
            name='cupo',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cupo total de pasajeros', null=True),
        ),
    ]
