# Generated by Django 4.2 on 2025-09-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0010_alter_salidapaquete_cupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='modalidad',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('fijo', 'Fijo')], default='flexible', help_text="Define si el paquete es 'flexible' (varios hoteles/rooms a elegir) o 'fijo' (hotel y habitación predefinidos).", max_length=10),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='habitacion_fija',
            field=models.ForeignKey(blank=True, help_text='Sólo para paquetes fijos: la habitación concreta de esta salida.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_fijas', to='hotel.habitacion'),
        ),
    ]
