# Generated by Django 4.2 on 2025-10-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0011_paquete_modalidad_salidapaquete_habitacion_fija'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidapaquete',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión % aplicada si el paquete es de distribuidora', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ganancia % aplicada si el paquete es propio', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='precio_venta_sugerido_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta sugerido máximo', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='salidapaquete',
            name='precio_venta_sugerido_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta sugerido mínimo', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_actual',
            field=models.DecimalField(decimal_places=2, help_text='Precio mínimo calculado (por persona, base sin comisión/ganancia)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio máximo calculado (puede ser nulo)', max_digits=12, null=True),
        ),
    ]
