# Generated by Django 4.2 on 2025-10-03 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicio', '0005_servicio_precio'),
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0012_salidapaquete_comision_salidapaquete_ganancia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='servicios',
        ),
        migrations.AlterField(
            model_name='paquete',
            name='cantidad_pasajeros',
            field=models.PositiveIntegerField(blank=True, help_text='Cantidad total de pasajeros (solo terrestre propio)', null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes/'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='modalidad',
            field=models.CharField(choices=[('flexible', 'Flexible'), ('fijo', 'Fijo')], default='flexible', help_text='Define si el paquete es flexible o fijo.', max_length=10),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='personalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='propio',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='comision',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='cupo',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='habitacion_fija',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salidas_fijas', to='hotel.habitacion'),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='hoteles',
            field=models.ManyToManyField(related_name='salidas_paquete', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_actual',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_venta_sugerido_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='precio_venta_sugerido_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='salidapaquete',
            name='senia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='temporada',
            name='paquetes',
            field=models.ManyToManyField(blank=True, related_name='temporadas', to='paquete.paquete'),
        ),
        migrations.CreateModel(
            name='PaqueteServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquete_servicios', to='paquete.paquete')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicio.servicio')),
            ],
            options={
                'verbose_name': 'Paquete Servicio',
                'verbose_name_plural': 'Paquetes Servicios',
                'unique_together': {('paquete', 'servicio')},
            },
        ),
    ]
