# Generated by Django 4.2 on 2025-10-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0013_remove_paquete_servicios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidapaquete',
            name='cupo',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Cantidad de asientos disponibles (solo aplica para paquetes terrestres propios).', null=True),
        ),
        migrations.CreateModel(
            name='CupoHabitacionSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.PositiveIntegerField(default=0)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_salidas', to='hotel.habitacion')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupos_habitaciones', to='paquete.salidapaquete')),
            ],
            options={
                'verbose_name': 'Cupo de Habitación por Salida',
                'verbose_name_plural': 'Cupos de Habitaciones por Salida',
                'unique_together': {('salida', 'habitacion')},
            },
        ),
    ]
