# Generated by Django 4.2 on 2025-10-20 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0014_alter_salidapaquete_cupo_cupohabitacionsalida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCatalogoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_catalogo', models.DecimalField(decimal_places=2, help_text='Precio base del catálogo de la distribuidora para esta habitación', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_catalogo_distribuidora', to='hotel.habitacion')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_catalogo', to='paquete.salidapaquete')),
            ],
            options={
                'verbose_name': 'Precio de Catálogo de Habitación',
                'verbose_name_plural': 'Precios de Catálogo de Habitaciones',
                'unique_together': {('salida', 'habitacion')},
            },
        ),
    ]
