# Generated by Claude Code on 2025-10-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_alter_habitacion_precio_noche'),
        ('paquete', '0015_preciocatalogohabitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioCatalogoHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_catalogo', models.DecimalField(decimal_places=2, help_text='Precio base del catálogo de la distribuidora para TODAS las habitaciones de este hotel', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_catalogo_distribuidora', to='hotel.hotel')),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_catalogo_hoteles', to='paquete.salidapaquete')),
            ],
            options={
                'verbose_name': 'Precio de Catálogo de Hotel',
                'verbose_name_plural': 'Precios de Catálogo de Hoteles',
                'unique_together': {('salida', 'hotel')},
            },
        ),
    ]
