# Generated by Django 4.2 on 2026-03-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0016_preciocatalogohotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='salidapaquete',
            name='codigo',
            field=models.CharField(blank=True, editable=False, help_text='Código único de la salida (ej: SAL-2026-0001)', max_length=20, null=True, unique=True),
        ),
    ]
