# Generated by Django 4.2 on 2026-03-22 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0018_populate_codigo_salida_paquete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salidapaquete',
            old_name='precio_actual',
            new_name='costo_base_desde',
        ),
        migrations.RenameField(
            model_name='salidapaquete',
            old_name='precio_final',
            new_name='costo_base_hasta',
        ),
    ]
