# Generated by Django 4.2 on 2026-03-29 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0019_rename_precio_actual_precio_final_to_costo_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCostoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('dividir_por_pasajeros', models.BooleanField(default=False, help_text='Si es True, el monto se divide por el cupo de la salida al calcular el costo por pasajero.')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Costo de Salida',
                'verbose_name_plural': 'Tipos de Costo de Salida',
                'db_table': 'TipoCostoSalida',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemCostoSalida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('salida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_costo', to='paquete.salidapaquete')),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_salida', to='paquete.tipocostosalida')),
            ],
            options={
                'verbose_name': 'Ítem de Costo por Salida',
                'verbose_name_plural': 'Ítems de Costo por Salida',
                'db_table': 'ItemCostoSalida',
                'unique_together': {('salida', 'tipo_costo')},
            },
        ),
        migrations.CreateModel(
            name='ItemCostoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_costo_default', to='paquete.paquete')),
                ('tipo_costo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_paquete', to='paquete.tipocostosalida')),
            ],
            options={
                'verbose_name': 'Ítem de Costo por Paquete',
                'verbose_name_plural': 'Ítems de Costo por Paquete',
                'db_table': 'ItemCostoPaquete',
                'unique_together': {('paquete', 'tipo_costo')},
            },
        ),
    ]
