# Generated by Django 4.2 on 2026-04-18 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0020_add_tipo_costo_salida_item_costo_precio_venta_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciocatalogohabitacion',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_catalogo_habitaciones', to='paquete.salidapaquete'),
        ),
    ]
