# Generated by Django 4.2 on 2026-04-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0021_rename_precios_catalogo_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocostosalida',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código estable para identificar el tipo (ej: BUS, COORDINADOR). No debe cambiarse una vez creado.', max_length=50, null=True, unique=True),
        ),
    ]
