# Generated by Django 4.2 on 2026-05-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paquete', '0024_deprecate_modalidad_fijo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='modalidad',
        ),
        migrations.RemoveField(
            model_name='salidapaquete',
            name='habitacion_fija',
        ),
    ]
