# Generated by Django 4.2 on 2025-08-16 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo_documento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('activo', models.BooleanField(default=True)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('tipo_persona', models.CharField(choices=[('F', 'Persona Física'), ('J', 'Persona Jurídica')], default='F', max_length=1)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='personas', to='tipo_documento.tipodocumento')),
            ],
            options={
                'verbose_name': 'Persona',
                'db_table': 'Persona',
            },
        ),
    ]
