# Generated by Django 4.2 on 2025-08-16 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaJuridica',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('razon_social', models.CharField(max_length=200)),
                ('representante', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('persona.persona',),
        ),
        migrations.RemoveField(
            model_name='persona',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nacionalidad',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='tipo_persona',
        ),
        migrations.AddField(
            model_name='persona',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PersonaFisica',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='persona.persona')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('nacionalidad', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('persona.persona',),
        ),
    ]
