# Generated by Django 4.2 on 2025-08-16 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_personajuridica_remove_persona_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personafisica',
            options={},
        ),
        migrations.AlterModelOptions(
            name='personajuridica',
            options={},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='polymorphic_ctype',
        ),
    ]
