# Generated by Django 4.2 on 2025-08-20 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nacionalidad', '0002_nacionalidad_en_uso'),
        ('persona', '0003_alter_personafisica_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personafisica',
            name='nacionalidad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='personas_fisicas', to='nacionalidad.nacionalidad'),
            preserve_default=False,
        ),
    ]
