# Generated by Django 4.2 on 2025-08-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_personafisica_nacionalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personafisica',
            options={'verbose_name': 'Persona Física'},
        ),
        migrations.AlterModelOptions(
            name='personajuridica',
            options={'verbose_name': 'Persona Jurídica'},
        ),
        migrations.AlterModelTable(
            name='personafisica',
            table='PersonaFisica',
        ),
        migrations.AlterModelTable(
            name='personajuridica',
            table='PersonaJuridica',
        ),
    ]
