# Generated by Django 4.2 on 2025-10-31 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_pasajero_por_asignar'),
        ('comprobante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='pasajero',
            field=models.OneToOneField(blank=True, help_text='Pasajero asociado a este voucher', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher', to='reserva.pasajero'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='codigo_voucher',
            field=models.CharField(editable=False, help_text='Código único del voucher (ej: RSV-2025-0001-PAX-001-VOUCHER)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='reserva',
            field=models.OneToOneField(blank=True, help_text='[LEGACY] Reserva asociada - se eliminará en migración futura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='voucher_legacy', to='reserva.reserva'),
        ),
    ]
