# Generated by Django 4.2 on 2024-03-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('estado', models.CharField(default='A', max_length=1)),
                ('formulario', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'db_table': 'Usuario',
            },
        ),
    ]
