# Generated by Django 4.2 on 2025-08-25 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_alter_rol_nombre'),
        ('empleado', '0004_alter_empleado_salario'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='empleado',
            field=models.OneToOneField(blank=True, help_text='Empleado asociado a este usuario del sistema', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='empleado.empleado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, help_text='Rol asignado al usuario', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='rol.rol'),
        ),
    ]
