# Generated by Django 4.2 on 2024-03-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='formulario',
        ),
    ]
