# Generated by Django 4.2 on 2025-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0005_alter_rol_nombre'),
        ('usuario', '0002_alter_usuario_empleado_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.AddField(
            model_name='usuario',
            name='roles',
            field=models.ManyToManyField(help_text='Roles asignado al usuario', related_name='usuarios', to='rol.rol'),
        ),
    ]
