# Generated by Django 4.2 on 2024-08-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_usuariosroles'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='en_uso',
            field=models.BooleanField(default=False),
        ),
    ]
