# Generated by Django 4.2 on 2025-08-27 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_usuario_must_change_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='must_change_password',
            new_name='debe_cambiar_contrasenia',
        ),
    ]
