# Generated by Django 4.2 on 2025-08-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_rename_must_change_password_usuario_debe_cambiar_contrasenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='debe_cambiar_contrasenia',
            field=models.BooleanField(default=True),
        ),
    ]
