# Generated by Django 4.2 on 2025-08-31 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('actividades', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Establecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='establecimientos', to='facturacion.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='TipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timbrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('inicio_vigencia', models.DateField()),
                ('fin_vigencia', models.DateField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timbrados', to='facturacion.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='SubtipoImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtipos', to='facturacion.tipoimpuesto')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoExpedicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_expedicion', to='facturacion.establecimiento')),
            ],
            options={
                'unique_together': {('establecimiento', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(editable=False, max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.empresa')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.establecimiento')),
                ('punto_expedicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.puntoexpedicion')),
                ('subtipo_impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.subtipoimpuesto')),
                ('timbrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.timbrado')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoimpuesto')),
            ],
            options={
                'unique_together': {('establecimiento', 'punto_expedicion', 'numero_factura')},
            },
        ),
    ]
