# Generated by Django 4.2 on 2025-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
        migrations.AddField(
            model_name='puntoexpedicion',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
    ]
