# Generated by Django 4.2 on 2025-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0002_establecimiento_nombre_puntoexpedicion_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', error_messages={'unique': 'Ya existe este nombre.'}, max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoexpedicion',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', error_messages={'unique': 'Ya existe este nombre.'}, max_length=100),
        ),
    ]
