# Generated by Django 4.2 on 2025-08-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0003_alter_establecimiento_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='establecimiento',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
        migrations.AlterField(
            model_name='puntoexpedicion',
            name='nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=100),
        ),
    ]
