# Generated by Django 4.2 on 2025-09-03 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0004_alter_establecimiento_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='es_configuracion',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='fecha_emision',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='numero_factura',
            field=models.CharField(blank=True, editable=False, max_length=15, null=True),
        ),
    ]
