# Generated by Django 4.2 on 2025-09-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0005_facturaelectronica_es_configuracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='punto_expedicion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='facturacion.puntoexpedicion'),
        ),
    ]
