# Generated by Django 4.2 on 2025-09-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0006_alter_facturaelectronica_punto_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='establecimiento',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puntoexpedicion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subtipoimpuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timbrado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tipoimpuesto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
