# Generated by Django 4.2 on 2025-10-31 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_pasajero_por_asignar'),
        ('moneda', '0001_initial'),
        ('facturacion', '0007_empresa_activo_establecimiento_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_direccion',
            field=models.CharField(blank=True, help_text='Dirección del cliente', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_email',
            field=models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_nombre',
            field=models.CharField(blank=True, help_text='Nombre o razón social del cliente', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_numero_documento',
            field=models.CharField(blank=True, help_text='Número de documento del cliente', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Teléfono del cliente', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_tipo_documento',
            field=models.CharField(blank=True, help_text='Tipo de documento: RUC, CI, etc.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='condicion_venta',
            field=models.CharField(blank=True, choices=[('contado', 'Contado'), ('credito', 'Crédito')], default='contado', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda de la factura', null=True, on_delete=django.db.models.deletion.PROTECT, to='moneda.moneda'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='reserva',
            field=models.ForeignKey(blank=True, help_text='Reserva asociada a esta factura', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='reserva.reserva'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_exenta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total de operaciones exentas', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_general',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total general de la factura', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_gravada_10',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total gravado IVA 10%', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_gravada_5',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total gravado IVA 5%', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_iva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total IVA', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_iva_10',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA 10%', max_digits=12),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_iva_5',
            field=models.DecimalField(decimal_places=2, default=0, help_text='IVA 5%', max_digits=12),
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(help_text='Número de línea en la factura')),
                ('descripcion', models.CharField(help_text='Descripción del producto o servicio', max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad de unidades', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario', max_digits=12)),
                ('monto_exenta', models.DecimalField(decimal_places=2, default=0, help_text='Monto exento de IVA', max_digits=12)),
                ('monto_gravada_5', models.DecimalField(decimal_places=2, default=0, help_text='Monto gravado con IVA 5%', max_digits=12)),
                ('monto_gravada_10', models.DecimalField(decimal_places=2, default=0, help_text='Monto gravado con IVA 10%', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del ítem (cantidad * precio_unitario)', max_digits=12)),
                ('factura', models.ForeignKey(help_text='Factura a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.facturaelectronica')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
                'ordering': ['numero_item'],
                'unique_together': {('factura', 'numero_item')},
            },
        ),
    ]
