# Generated by Django 4.2 on 2025-11-01 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_reserva_modalidad_facturacion'),
        ('facturacion', '0008_facturaelectronica_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='pasajero',
            field=models.ForeignKey(blank=True, help_text="Pasajero específico (solo si tipo_facturacion='por_pasajero')", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='reserva.pasajero'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tipo_facturacion',
            field=models.CharField(blank=True, choices=[('total', 'Factura Total (Reserva Completa)'), ('por_pasajero', 'Factura por Pasajero Individual')], default='total', help_text='Modalidad de facturación: total o por pasajero', max_length=20, null=True),
        ),
    ]
