# Generated by Django 4.2 on 2025-11-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0009_facturaelectronica_pasajero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='pdf_generado',
            field=models.FileField(blank=True, help_text='PDF de la factura', null=True, upload_to='facturas/pdf/'),
        ),
    ]
