# Generated by Django 4.2 on 2025-11-03 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0005_alter_personafisica_options_and_more'),
        ('facturacion', '0010_facturaelectronica_pdf_generado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre completo o razón social del cliente', max_length=200)),
                ('tipo_documento', models.CharField(choices=[('CI', 'Cédula de Identidad'), ('RUC', 'RUC'), ('PASAPORTE', 'Pasaporte'), ('OTRO', 'Otro')], help_text='Tipo de documento de identidad', max_length=20)),
                ('numero_documento', models.CharField(help_text='Número de documento (CI, RUC, Pasaporte, etc.)', max_length=20)),
                ('direccion', models.CharField(blank=True, help_text='Dirección del cliente', max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, help_text='Correo electrónico', max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(blank=True, help_text='Persona del sistema asociada (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_facturacion', to='persona.persona')),
            ],
            options={
                'verbose_name': 'Cliente de Facturación',
                'verbose_name_plural': 'Clientes de Facturación',
                'db_table': 'cliente_facturacion',
            },
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='cliente_facturacion',
            field=models.ForeignKey(blank=True, help_text='Cliente a nombre del cual se emite la factura (tercero opcional). Si se especifica, sobrescribe los datos del titular/pasajero', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='facturacion.clientefacturacion'),
        ),
        migrations.AddIndex(
            model_name='clientefacturacion',
            index=models.Index(fields=['numero_documento', 'tipo_documento'], name='cliente_fac_numero__cf6242_idx'),
        ),
        migrations.AddIndex(
            model_name='clientefacturacion',
            index=models.Index(fields=['activo'], name='cliente_fac_activo_20284d_idx'),
        ),
    ]
