# Generated by Django 4.2 on 2025-11-03 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_documento', '0002_alter_tipodocumento_table'),
        ('facturacion', '0011_clientefacturacion_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientefacturacion',
            new_name='cliente_fac_numero__b6635b_idx',
            old_name='cliente_fac_numero__cf6242_idx',
        ),
        migrations.AlterField(
            model_name='clientefacturacion',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento de identidad', on_delete=django.db.models.deletion.PROTECT, related_name='clientes_facturacion', to='tipo_documento.tipodocumento'),
        ),
    ]
