# Generated by Django 4.2 on 2025-11-06 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0012_rename_cliente_fac_numero__cf6242_idx_cliente_fac_numero__b6635b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del crédito (calculada: fecha_emision + plazo_credito_dias)', null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='plazo_credito_dias',
            field=models.IntegerField(blank=True, help_text='Plazo en días para pago a crédito (ej: 30, 60, 90)', null=True),
        ),
    ]
