# Generated by Django 4.2 on 2025-11-06 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0013_facturaelectronica_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facturaelectronica',
            name='plazo_credito_dias',
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del crédito. Para crédito: fecha_salida - 15 días', null=True),
        ),
    ]
