# Generated by Django 4.2 on 2025-11-07 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
        ('facturacion', '0014_remove_facturaelectronica_plazo_credito_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCreditoElectronica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota_credito', models.CharField(editable=False, help_text='Número correlativo de la nota de crédito (formato: XXX-XXX-XXXXXXX)', max_length=15)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de emisión de la nota de crédito')),
                ('tipo_nota', models.CharField(choices=[('total', 'Anulación Total'), ('parcial', 'Anulación Parcial')], help_text='Tipo de anulación: total (100% de la factura) o parcial (monto menor)', max_length=20)),
                ('motivo', models.CharField(choices=[('cancelacion_reserva', 'Cancelación de Reserva'), ('devolucion', 'Devolución'), ('descuento', 'Descuento/Bonificación'), ('error_facturacion', 'Error en Facturación'), ('ajuste', 'Ajuste de Precio'), ('otro', 'Otro')], help_text='Motivo de la emisión de la nota de crédito', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la nota de crédito', null=True)),
                ('cliente_tipo_documento', models.CharField(max_length=50)),
                ('cliente_numero_documento', models.CharField(max_length=20)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_direccion', models.CharField(blank=True, max_length=200)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('total_exenta', models.DecimalField(decimal_places=2, default=0, help_text='Total de operaciones exentas acreditadas', max_digits=15)),
                ('total_gravada_5', models.DecimalField(decimal_places=2, default=0, help_text='Total gravado IVA 5% acreditado', max_digits=15)),
                ('total_gravada_10', models.DecimalField(decimal_places=2, default=0, help_text='Total gravado IVA 10% acreditado', max_digits=15)),
                ('total_iva_5', models.DecimalField(decimal_places=2, default=0, help_text='IVA 5% acreditado', max_digits=15)),
                ('total_iva_10', models.DecimalField(decimal_places=2, default=0, help_text='IVA 10% acreditado', max_digits=15)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0, help_text='Total IVA acreditado', max_digits=15)),
                ('total_general', models.DecimalField(decimal_places=2, default=0, help_text='Total general acreditado (monto que se resta de la factura)', max_digits=15)),
                ('pdf_generado', models.FileField(blank=True, help_text='PDF de la nota de crédito', null=True, upload_to='facturas/notas_credito/pdf/')),
                ('activo', models.BooleanField(default=True, help_text='Indica si la nota de crédito está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.empresa')),
                ('establecimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.establecimiento')),
                ('factura_afectada', models.ForeignKey(help_text='Factura que se está anulando (total o parcialmente)', on_delete=django.db.models.deletion.PROTECT, related_name='notas_credito', to='facturacion.facturaelectronica')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='moneda.moneda')),
                ('punto_expedicion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.puntoexpedicion')),
                ('subtipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.subtipoimpuesto')),
                ('timbrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.timbrado')),
                ('tipo_impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.tipoimpuesto')),
            ],
            options={
                'verbose_name': 'Nota de Crédito Electrónica',
                'verbose_name_plural': 'Notas de Crédito Electrónicas',
                'db_table': 'nota_credito_electronica',
                'ordering': ['-fecha_emision'],
                'unique_together': {('establecimiento', 'punto_expedicion', 'numero_nota_credito')},
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_item', models.PositiveIntegerField(help_text='Número de línea en la nota de crédito')),
                ('descripcion', models.CharField(help_text='Descripción del producto/servicio que se está acreditando', max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Cantidad a acreditar', max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario del item acreditado', max_digits=15)),
                ('monto_exenta', models.DecimalField(decimal_places=2, default=0, help_text='Monto exento de IVA acreditado', max_digits=15)),
                ('monto_gravada_5', models.DecimalField(decimal_places=2, default=0, help_text='Monto gravado IVA 5% acreditado', max_digits=15)),
                ('monto_gravada_10', models.DecimalField(decimal_places=2, default=0, help_text='Monto gravado IVA 10% acreditado', max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item (cantidad * precio_unitario)', max_digits=15)),
                ('detalle_factura_afectado', models.ForeignKey(blank=True, help_text='Detalle de factura que se está acreditando (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_nota_credito', to='facturacion.detallefactura')),
                ('nota_credito', models.ForeignKey(help_text='Nota de crédito a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.notacreditoelectronica')),
            ],
            options={
                'verbose_name': 'Detalle de Nota de Crédito',
                'verbose_name_plural': 'Detalles de Nota de Crédito',
                'db_table': 'detalle_nota_credito',
                'ordering': ['numero_item'],
                'unique_together': {('nota_credito', 'numero_item')},
            },
        ),
    ]
