# Generated by Django 4.2 on 2025-11-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0015_notacreditoelectronica_detallenotacredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notacreditoelectronica',
            name='motivo',
            field=models.CharField(choices=[('1', 'Devolución y Ajuste de precios'), ('2', 'Devolución'), ('3', 'Descuento'), ('4', 'Bonificación'), ('5', 'Crédito incobrable'), ('6', 'Recupero de costo'), ('7', 'Recupero de gasto'), ('8', 'Ajuste de precio')], help_text='Código según campo E401 (iMotEmi) de SIFEN. Este valor se enviará directamente en el XML', max_length=1, verbose_name='Motivo de emisión'),
        ),
    ]
