# Generated by Django 4.2 on 2025-11-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0002_cotizacionmoneda_and_more'),
        ('facturacion', '0016_alter_notacreditoelectronica_motivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacturaCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Monto en la moneda original (ej: USD)', max_digits=12)),
                ('monto_convertido', models.DecimalField(decimal_places=2, help_text='Monto convertido a guaraníes', max_digits=12)),
                ('tasa_conversion', models.DecimalField(decimal_places=2, help_text='Tasa de conversión aplicada (valor en guaraníes de 1 unidad de moneda original)', max_digits=12)),
                ('fecha_conversion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la conversión')),
                ('cotizacion', models.ForeignKey(help_text='Cotización utilizada para la conversión', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_convertidas', to='moneda.cotizacionmoneda')),
                ('factura', models.OneToOneField(help_text='Factura que utilizó conversión de moneda', on_delete=django.db.models.deletion.PROTECT, related_name='conversion_moneda', to='facturacion.facturaelectronica')),
                ('moneda_original', models.ForeignKey(help_text='Moneda original del paquete/salida', on_delete=django.db.models.deletion.PROTECT, related_name='facturas_convertidas_desde', to='moneda.moneda')),
            ],
            options={
                'verbose_name': 'Conversión de Factura',
                'verbose_name_plural': 'Conversiones de Facturas',
                'db_table': 'factura_cotizacion',
                'ordering': ['-fecha_conversion'],
            },
        ),
    ]
