# Generated by Django 4.2 on 2025-11-09 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0002_cotizacionmoneda_and_more'),
        ('facturacion', '0017_facturacotizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='moneda_original',
            field=models.ForeignKey(blank=True, help_text='Moneda original del paquete antes de conversión (ej: USD). Null si no hubo conversión.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_moneda_original', to='moneda.moneda'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='tasa_conversion_aplicada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tasa de conversión aplicada (valor en guaraníes de 1 unidad de moneda original). Null si no hubo conversión.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='total_original',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total de la factura en moneda original antes de conversión. Null si no hubo conversión.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='facturaelectronica',
            name='moneda',
            field=models.ForeignKey(blank=True, help_text='Moneda de la factura (siempre PYG - guaraníes)', null=True, on_delete=django.db.models.deletion.PROTECT, to='moneda.moneda'),
        ),
    ]
