# Generated by Django 4.2 on 2025-11-20 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facturacion', '0018_facturaelectronica_moneda_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaelectronica',
            name='fecha_anulacion',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se anuló la factura', null=True),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='motivo_anulacion',
            field=models.TextField(blank=True, help_text='Motivo de la anulación de la factura'),
        ),
        migrations.AddField(
            model_name='facturaelectronica',
            name='usuario_anulacion',
            field=models.ForeignKey(blank=True, help_text='Usuario que anuló la factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
    ]
