# Generated by Django 4.2 on 2025-11-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0019_facturaelectronica_fecha_anulacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaelectronica',
            name='motivo_anulacion',
            field=models.CharField(blank=True, choices=[('1', 'Error en datos de emisor'), ('2', 'Error en datos del receptor'), ('3', 'Error en datos de la operación'), ('4', 'Operación no realizada'), ('5', 'Por acuerdo entre las partes')], help_text='Motivo de la anulación de la factura (código dMotEmi según normativa SET)', max_length=1, null=True),
        ),
    ]
